const MODEL_ICONS: Record<string, string> = {
  deepseek: '/icon/deepseek.svg',
  openai: '/icon/openai.svg',
  anthropic: '/icon/anthropic.svg',
  claude: '/icon/claude.svg',
  gemini: '/icon/gemini.svg',
  google: '/icon/google.svg',
  googlecloud: '/icon/googlecloud.svg',
  palm: '/icon/palm.svg',
  gemma: '/icon/gemma.svg',
  qwen: '/icon/qwen.svg',
  alibaba: '/icon/alibaba.svg',
  kimi: '/icon/kimi.svg',
  moonshot: '/icon/kimi.svg',
  chatglm: '/icon/chatglm.svg',
  zhipu: '/icon/zhipu.svg',
  zai: '/icon/zhipu.svg',
  grok: '/icon/grok.svg',
  xai: '/icon/xai.svg',
  mistral: '/icon/mistral.svg',
  cohere: '/icon/cohere.svg',
  meta: '/icon/meta.svg',
  llama: '/icon/meta.svg',
  ollama: '/icon/ollama.svg',
  huggingface: '/icon/huggingface.svg',
  azure: '/icon/azure.svg',
  aws: '/icon/aws.svg',
  amazon: '/icon/aws.svg',
  baidu: '/icon/baidu.svg',
  wenxin: '/icon/wenxin.svg',
  ernie: '/icon/wenxin.svg',
  bytedance: '/icon/bytedance.svg',
  doubao: '/icon/doubao.png',
  "seed": '/icon/doubao.png',
  tencent: '/icon/tencent.svg',
  hunyuan: '/icon/hunyuan.svg',
  minimax: '/icon/minimax.svg',
  zeroone: '/icon/zeroone.svg',
  '01ai': '/icon/zeroone.svg',
  nvidia: '/icon/nvidia.svg',
  stability: '/icon/stability.svg',
  github: '/icon/github.svg',
  githubcopilot: '/icon/githubcopilot.svg',
  copilot: '/icon/githubcopilot.svg',
  perplexity: '/icon/perplexity.svg',
  midjourney: '/icon/midjourney.svg',
  notion: '/icon/notion.svg',
  vercel: '/icon/vercel.svg',
  huawei: '/icon/huawei.svg',
  cloudflare: '/icon/cloudflare.svg',
  xiaomi: '/icon/xiaomimimo.svg',
  xiaomimimo: '/icon/xiaomimimo.svg',
  aionlabs: '/icon/aionlabs.png',
  allenai: '/icon/allenai.png',
  arceeai: '/icon/arceeai.jpg',
  dotsstudio: '/icon/dotsstudio.png',
  meituan: '/icon/meituan.png',
  microsoft: '/icon/microsoft.png',
  anthracite: '/icon/anthracite.png',

  openrouter: '/icon/openrouter.svg',
  siliconflow: '/icon/siliconflow.svg',
  modelscope: '/icon/modelscope-color.svg',
  novita: '/icon/novita.svg',
  newapi: '/icon/newapi.svg',
  aihubmix: '/icon/aihubmix-color.svg',
  crazyrouter: '/icon/crazyrouter.svg',
  subrouter: '/icon/subrouter.svg',
  teamorouter: '/icon/TeamoRouter-icon-dark.png',
  shengsuanyun: '/icon/shengsuanyun.svg',
  micu: '/icon/micu.svg',
  ucloud: '/icon/ucloud.svg',
  sssaicode: '/icon/sssaicode.svg',
  stepfun: '/icon/stepfun.svg',
  catcoder: '/icon/catcoder.svg',
  bailian: '/icon/bailian.svg',
  ppio: '/icon/ppio.svg',
  mcp: '/icon/mcp.svg',
  rc: '/icon/rc.svg',
  lioncc: '/icon/lioncc.svg',
  longcat: '/icon/longcat-color.svg',
  opencode: '/icon/opencode-logo-light.svg',
  amux: '/icon/amuxapi-icon.svg',
  claw: '/icon/claw.svg',
  openclaw: '/icon/claw.svg',
  cubence: '/icon/cubence.svg',
  packycode: '/icon/packycode.svg',
  zenmux: '/icon/amuxapi-icon.svg',

  a6api: '/icon/a6-icon.png',
  apikeyfun: '/icon/apikeyfun.png',
  apinebula: '/icon/apinebula_icon.png',
  atlascloud: '/icon/atlascloud_icon.png',
  byteplus: '/icon/byteplus.png',
  ccsub: '/icon/ccsub.svg',
  claudeapi: '/icon/ClaudeApi.png',
  claudecn: '/icon/claudecn.png',
  cherryin: '/icon/cherryin.png',
  code0: '/icon/code0.png',
  eflowcode: '/icon/eflowcode.png',
  etok: '/icon/etok.png',
  fenno: '/icon/fenno-icon.webp',
  hermes: '/icon/hermes.png',
  nousresearch: '/icon/hermes.png',
  huoshan: '/icon/huoshan.png',
  nekocode: '/icon/nekocode-icon.png',
  pateway: '/icon/pateway.jpg',
  pipellm: '/icon/pipellm.png',
  qiniu: '/icon/qiniu.png',
  relaxcode: '/icon/relaxcode.png',
  runapi: '/icon/runapi.jpg',
  sudocode: '/icon/sudocode.png',
  sudocus: '/icon/sudocode-us.png',
  unity2: '/icon/unity2.png',
  xycai: '/icon/xycai-icon.png',
  zetaapi: '/icon/zetaapi-icon.png',
};

const ICON_KEYS = Object.keys(MODEL_ICONS).sort((a, b) => b.length - a.length);

function normalize(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '');
}

export function resolveModelIcon(name: string): string | null {
  if (!name) return null;
  const norm = normalize(name);
  if (!norm) return null;

  const direct = MODEL_ICONS[norm];
  if (direct) return direct;

  for (const key of ICON_KEYS) {
    if (key.length < 3) continue;
    const icon = MODEL_ICONS[key];
    if (icon && norm.includes(key)) return icon;
  }
  return null;
}
