[package]
name = "libra-platform"
version = "0.1.0"
edition = "2021"

[dependencies]
libra-common = { path = "../libra-common" }
tokio = { workspace = true }
serde_json = { workspace = true }
sysinfo = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winreg", "psapi", "tlhelp32", "memoryapi", "processthreadsapi", "handleapi", "sysinfoapi", "winuser", "wincrypt", "shellapi"] }
