[package]
name = "powershell-module"
version = "0.1.0"
edition = "2021"

[lib]
name = "powershell_module"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = { workspace = true }
libra-common = { path = "../../libra-common" }
libra-psinline = { path = "../../libra-psinline" }
libra-syscalls = { path = "../../libra-syscalls" }
