[package]
name = "libra-modules"
version = "0.1.0"
edition = "2021"

[dependencies]
libra-common = { path = "../libra-common" }
libra-platform = { path = "../libra-platform" }
libra-comm = { path = "../libra-comm" }
libra-crypto = { path = "../libra-crypto" }
tokio = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
reqwest = { workspace = true }
sysinfo = { workspace = true }
futures-util = { workspace = true }
regex = { workspace = true }
image = { workspace = true }
windows = { workspace = true }
windows-core = "0.58"
