[package]
name = "script-module"
version = "0.1.0"
edition = "2021"

[lib]
name = "script_module"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = { workspace = true }
rquickjs = { workspace = true }
libra-common = { path = "../../libra-common" }
libra-psinline = { path = "../../libra-psinline" }
libra-platform = { path = "../../libra-platform" }
