[package]
name = "recon-module"
version = "0.1.0"
edition = "2021"

[lib]
name = "recon_module"
crate-type = ["cdylib"]

[dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
sysinfo = { workspace = true }
futures-util = { workspace = true }
windows = { workspace = true }
windows-core = "0.58"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
